export {
  AUTH_ERROR_EVENT_NAME,
  AUTH_EVENT_NAME,
  AUTH_INIT_ERROR_EVENT_NAME,
  AUTH_LOGOUT_EVENT_NAME,
  AUTH_READY_EVENT_NAME,
  AUTH_REFRESH_TOKEN_ERROR_EVENT_NAME,
  AUTH_REFRESH_TOKEN_SUCCESS_EVENT_NAME,
  AUTH_SUCCESS_EVENT_NAME,
  AUTH_TOKEN_EXPIRED_EVENT_NAME,
} from "@/shared/api/auth/config/auth.ts";
