export {
  ACCEPT_HEADER_NAME,
  CONTENT_TYPE_HEADER_NAME,
  HTTP_METHODS,
  JSON_CONTENT_TYPE,
  MULTIPART_FORM_DATA_CONTENT_TYPE,
  OCTET_STREAM_CONTENT_TYPE,
  PLAIN_TEXT_CONTENT_TYPE,
} from "@/shared/api/consts/api.ts";
